{"name": "test_update_task_negative", "status": "passed", "description": "Негативный тест: передача некорректных данных при обновлении задачи.", "steps": [{"name": "Обновление задачи по ID: '86a82fy9t'", "status": "passed", "steps": [{"name": "PUT /task/86a82fy9t", "status": "passed", "start": 1745075061452, "stop": 1745075061597}], "parameters": [{"name": "task_id", "value": "'86a82fy9t'"}, {"name": "task_update", "value": "'invalid_payload'"}], "start": 1745075061452, "stop": 1745075061597}], "start": 1745075061452, "stop": 1745075061597, "uuid": "eadec9bc-c519-4c1b-b8d9-2cf7b8e1ea22", "historyId": "fe5e41104959de7eee0a8bdfa066bd06", "testCaseId": "fe5e41104959de7eee0a8bdfa066bd06", "fullName": "tests.api.test_tasks#test_update_task_negative", "labels": [{"name": "feature", "value": "Задачи"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "host", "value": "DESKTOP-77BDOFA"}, {"name": "thread", "value": "17384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}